# Generated by Django 5.2.5 on 2025-08-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
